---
kind: pipeline
name: default

steps:
- name: ServiceA
  image: python:3.7.9-stretch
  commands:
  - echo after
  - echo "${DRONE_COMMIT_SHA}"
  - echo before
  - echo "${DRONE_COMMIT_BEFORE}"
trigger:
  event:
  - pull_request