---
kind: pipeline
name: default

steps:
- name: ServiceA
  image: python:3.7.9-stretch
  commands:
  - git diff --name-only origin/main
  - echo after
  - ${DRONE_COMMIT_AFTER}
  - echo before
  - ${DRONE_COMMIT_BEFORE}