---
kind: pipeline
name: default

steps:
- name: ServiceA
  image: python:3.7.9-stretch
  commands:
  - git diff --name-only origin/main
  - echo after
  - echo "${DRONE_COMMIT_AFTER}"
  - echo before
  - echo "${DRONE_COMMIT_BEFORE}"